"""
Module: app/ai/guardrails/hallucination.py

Hallucination guard — validates that LLM-generated explanations
do not contradict or invent information beyond the structured data.

Strategy:
- Check that scheme amounts mentioned in LLM text match the data.
- Strip any mention of scheme IDs or rules not in the source data.
- This is a lightweight post-processing step, not a semantic verifier.
"""

from __future__ import annotations

import re
from typing import Optional

from app.ai.eligibility.rules import SchemeEligibilityRules


class HallucinationGuard:
    """
    Lightweight validation of LLM-generated explanation text.

    Checks that the text does not contain clearly fabricated scheme IDs.
    Does NOT attempt deep semantic verification.
    """

    # Patterns that suggest the LLM may be inventing rules
    SUSPICIOUS_PATTERNS = [
        r"\bguaranteed\s+to\s+get\b",
        r"\b100%\s+eligible\b",
        r"\bno\s+income\s+limit\b",
        r"\bapply\s+today\s+and\s+get\b",
    ]

    @classmethod
    def validate(
        cls,
        llm_text: str,
        scheme_rules: Optional[SchemeEligibilityRules] = None,
    ) -> str:
        """
        Validate and sanitize LLM-generated explanation text.

        Args:
            llm_text:      Raw text generated by LLM.
            scheme_rules:  Source scheme rules (used for cross-checking).

        Returns:
            Sanitized text, or original if no issues found.
        """
        if not llm_text:
            return llm_text

        sanitized = llm_text

        # Remove suspicious guarantee language
        for pattern in cls.SUSPICIOUS_PATTERNS:
            if re.search(pattern, sanitized, re.IGNORECASE):
                # Replace with a safe disclaimer note
                sanitized = re.sub(
                    pattern,
                    "[eligibility subject to official verification]",
                    sanitized,
                    flags=re.IGNORECASE,
                )

        return sanitized
