"""
Module: app/ai/eligibility/rules.py

Pydantic data models for scheme eligibility rule definitions.

Rules are loaded from structured JSON records — never invented at runtime.
The engine reads these models and evaluates them deterministically.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Union
from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Supported operators (mirrors conditions.py for schema validation)
# ---------------------------------------------------------------------------

class Operator(str, Enum):
    EQ      = "="
    NEQ     = "!="
    LT      = "<"
    LTE     = "<="
    GT      = ">"
    GTE     = ">="
    IN      = "IN"
    NOT_IN  = "NOT_IN"


# ---------------------------------------------------------------------------
# A single eligibility condition
# ---------------------------------------------------------------------------

class EligibilityCondition(BaseModel):
    """
    One atomic condition from a scheme's eligibility rule set.

    Example JSON:
        {
            "field": "age",
            "operator": ">=",
            "value": 18,
            "description": "Applicant must be at least 18 years old",
            "required": true
        }
    """
    field: str = Field(
        ...,
        description="Profile field to evaluate (e.g. 'age', 'gender', 'annual_income')."
    )
    operator: Operator = Field(
        ...,
        description="Comparison operator."
    )
    value: Union[str, int, float, List[Any]] = Field(
        ...,
        description="Target value(s) to compare the profile field against."
    )
    description: str = Field(
        ...,
        description="Human-readable description of this condition."
    )
    required: bool = Field(
        default=True,
        description=(
            "If True, this condition MUST pass for eligibility. "
            "If False, a missing/unknown profile value triggers 'needs_verification' "
            "rather than 'not_eligible'."
        )
    )

    @model_validator(mode="after")
    def validate_in_value_is_list(self) -> "EligibilityCondition":
        if self.operator in (Operator.IN, Operator.NOT_IN):
            if not isinstance(self.value, list):
                raise ValueError(
                    f"Operator '{self.operator}' requires 'value' to be a list, "
                    f"got {type(self.value).__name__}."
                )
        return self


# ---------------------------------------------------------------------------
# A complete rule set for one scheme
# ---------------------------------------------------------------------------

class SchemeEligibilityRules(BaseModel):
    """
    All eligibility rules for a single government scheme.

    Loaded from a JSON record; NEVER generated by an LLM.
    """
    scheme_id: str = Field(..., description="Unique scheme identifier.")
    scheme_name: str = Field(..., description="Display name of the scheme.")
    ministry: Optional[str] = Field(default=None, description="Issuing ministry/department.")
    description: Optional[str] = Field(default=None, description="Brief scheme description.")
    conditions: List[EligibilityCondition] = Field(
        default_factory=list,
        description="List of eligibility conditions. All required=True conditions must pass."
    )
    benefit_summary: Optional[str] = Field(
        default=None,
        description="Short description of the benefit (e.g. subsidy amount, loan limit)."
    )
    application_url: Optional[str] = Field(
        default=None,
        description="Official portal URL for application."
    )


# ---------------------------------------------------------------------------
# Registry loader (in-memory, from JSON files or dicts)
# ---------------------------------------------------------------------------

class SchemeRulesRegistry:
    """
    In-memory store of SchemeEligibilityRules objects.
    Populated from JSON at startup — no LLM involvement.
    """

    def __init__(self) -> None:
        self._rules: dict[str, SchemeEligibilityRules] = {}

    def load(self, scheme_rules: SchemeEligibilityRules) -> None:
        """Register rules for a single scheme."""
        self._rules[scheme_rules.scheme_id] = scheme_rules

    def load_many(self, items: List[SchemeEligibilityRules]) -> None:
        """Register rules for multiple schemes."""
        for item in items:
            self.load(item)

    def load_from_dict(self, data: dict) -> None:
        """Parse and register a scheme from a raw dict (e.g. loaded from JSON)."""
        self.load(SchemeEligibilityRules.model_validate(data))

    def get(self, scheme_id: str) -> Optional[SchemeEligibilityRules]:
        return self._rules.get(scheme_id)

    def all(self) -> List[SchemeEligibilityRules]:
        return list(self._rules.values())

    def ids(self) -> List[str]:
        return list(self._rules.keys())

    def __len__(self) -> int:
        return len(self._rules)
